server:
  port: 8080

spring:
  application:
    name: core-service
  main:
    web-application-type: servlet
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartmuseum

museum:
  space-id: smart-museum-chicago   # Topic namespace

  websocket:
    path: /ws

  services:
    positioning:
      enabled: true
      base-url: http://localhost:8081
      endpoint: /internal/positioning/readings
      timeout-ms: 2000

    artinfo:
      enabled: true
      base-url: http://localhost:8082
      endpoint: /internal/art/nearest
      timeout-ms: 500

    heatmap:
      enabled: true
      base-url: http://localhost:8083
      endpoint: /api/heatmap
      timeout-ms: 500

  mqtt:
    broker-url: tcp://localhost:1883
    client-id: core-service
    # Museum-specific topic naming
    topics:
      heatmap: "${museum.space-id}/heatmap/grid"
      registry-register: "${museum.space-id}/registry/register"
      registry-heartbeat: "${museum.space-id}/registry/heartbeat"

  registry:
    heartbeat-timeout-ms: 60000   # 60 секундын дотор heartbeat ирэхгүй бол OFFLINE
    check-interval-ms: 15000      # 15 секунд тутам шалгана