server:
  port: 8080

spring:
  application:
    name: core-service
  main:
    web-application-type: servlet

museum:
  websocket:
    path: /ws

  services:
    positioning:
      enabled: true
      base-url: http://localhost:8081
      endpoint: /internal/positioning/readings
      timeout-ms: 2000

    artinfo:
      enabled: true
      base-url: http://localhost:8082
      endpoint: /internal/art/nearest
      timeout-ms: 500

    heatmap:
      enabled: true
      base-url: http://localhost:8083
      endpoint: /api/heatmap
      timeout-ms: 500

  mqtt:
    broker-url: tcp://localhost:1883
    client-id: core-service
    heatmap-topic: museum/heatmap/grid